[build]
  # Directory to run the build command from
  base = "frontend"
  
  # Build command
  command = "npm install && npm run build"
  
  # Directory to publish (relative to base)
  publish = "dist"

# Environment variables for production
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"